spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      hbm2ddl:
        auto: update
    show_sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
